### PR TITLE
Add command and keybindings to sort results

### PR DESCRIPTION
**Pull request by misterbuckley**
This does a few things:
- Improves the PostBufferFormat function for psql to remove the "(x results)" and blank lines psql appends to the end of query results
- Adds a SQHSortResults command to sort results based on the column the cursor is located on
- Adds default keybindings for s and S to sort results by the current column in ascending or descending order (respectively)

A few things to note:
- I don't have mysql set up so I haven't actually tested whether or not this works for mysql, but from what I see for how mysql returns results, I believe it should work. If someone who uses mysql could test it real quick, that'd be great
- It will not work correctly in buffers that have results from more than one query in them. Right now, executing a file/block in psql with more than one select in it only returns results for the last select statement, so once that gets fixed, I can fix this

btw this is apola from reddit fyi :)

### CODE REVIEW

**Comment by joereynolds** [comment]
Hey, great idea, thanks for the pr!

I'm a MySQL user so I can test this in work tomorrow :D 
Once again, thanks!

Update: 

on `S` in a MySQL result I get this

image

**Comment by joereynolds** [comment]
the `S` works fine however `s` does nothing on its own for me atleast. I am using [vim-sandwich](https://github.com/machakann/vim-sandwich) which overwrites the native `s` command. 

Perhaps the plugin needs to be installed after vim-sandwich?

Also there's another issue here:

image

Here's another issue on how it sorts numbers:

image

Still, thanks for the work so far, it's looking good!

**Comment by misterbuckley** [comment]
Alright I've fixed that error with the SQHSortResults command.

For the mappings being overwritten, I thought the mappings being in the ftplugin for SQHResults would have taken care of that since the mappings get created on opening the buffer, but maybe vim-sandwich does something to overwrite them. Try it again with my new fixes and see if that works for you, otherwise we'll have to find another solution. I'll try and figure out why they might be getting overwritten like that.

As for the numbers being sorted incorrectly, I kinda saw that one coming. `:SQHSortResults -n` should sort it correctly.

**Comment by joereynolds** [comment]
This is looking way better! 
There are still a few small issues though

1) If you sort on a row that isn't valid, you get this error
    `sort: field number is zero: invalid field specification ‘0’`
Is it possible to check this beforehand to prevent this trying to sort invalid rows?

2) On a mysql result, if you sort with lowercase `s` It adds an extra row beneath the header (this is probably just the one from the bottom of the result). The result ends up looking like this

```
+------+--------------+
| __pk | _fk_id       |
+------+--------------+
+------+--------------+
| 1000 |            0 |
|  100 |            0 |
```

Whereas it should be

```
+------+--------------+
| __pk | _fk_id       |
+------+--------------+
| 1000 |            0 |
|  100 |            0 |
```

Thanks again for these pr's. It's a good feature to have

p.s. ignore the problem I'm having with sandwich, we can fix that forward, I'd like this feature in :)

**Comment by misterbuckley** [comment]
Yeah the issue with that extra row showing up was just the line from the bottom of the file. psql doesn't include a line around the outside of the table so I forgot to account for that. I've fixed it for now but I'm thinking I'll have to eventually come up with a better solution for determining which lines to sort, since inserting a row at the top of the file, for example, would cause it to sort the wrong lines.

**Comment by joereynolds** [comment]
A simple solution could be to just delete the bottom row from the mysql result anyway?
It's not really offering much and then it doesn't screw up this formatting

I'll take another look at it now :D

**Comment by joereynolds** [comment]
Okay one more issue and I think that's it. I've pulled down the latest stuff and it seems to be a row 'behind' when I sort.
 i.e. if I press `s` or `S` column 3, it actually sorts column 2

Here's a gif that hopefully explains better than I can

sort-bug

**Comment by misterbuckley** [comment]
Oh boy, thought I'd tested for that already. Here's hoping this fixes it once and for all

**Comment by joereynolds** [comment]
You beaut, it works perfectly!

**Pull request merged**
